
package osgi.common.util.modbustcp.slave.event;

/**
 * @author zhangchangchun
 * @since 2021年12月25日
 */
public enum ModbusSlaveEventType {
    HOLDINGREGISTER_READ_SUCCESS, HOLDINGREGISTER_READ_FAIL, HOLDINGREGISTER_SINGLE_WRITE_SUCCESS, HOLDINGREGISTER_SINGLE_WRITE_FAIL, HOLDINGREGISTER_MULTIPLE_WRITE_SUCCESS, HOLDINGREGISTER_MULTIPLE_WRITE_FAIL;
}
